security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_member_provider:
            entity:
                class: App\Entity\Member
                property: email  # Assurez-vous que votre entité Member a un champ 'email' utilisé comme identifiant


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_member_provider  # Utilisez le nouveau provider ici
            custom_authenticator: App\Security\UserLoginAuthenticator
            logout:
                path: app_logout  # Assurez-vous que cette route est correctement configurée
                target: app_login  # Où rediriger après la déconnexion


    access_control:
    # Exemples de contrôles d'accès
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur la plus basse pour bcrypt
                time_cost: 3 # Valeur la plus basse pour argon
                memory_cost: 10 # Valeur la plus basse pour argon


